name: Commit Check

on:
  push:
    branches:
      - main

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Check if README.md contains name
        run: |
          if grep -q "Emanuele" README.md; then
            echo "README.md contains your name. Commit allowed."
          else
            echo "ERROR: README.md does not contain your name. Commit not allowed."
            exit 1
    
